# aholyc - another Holy-C compiler. Zero external dependencies: only cc + make.
CC ?= cc
AR ?= ar
CFLAGS ?= -Os -Wall -Wextra -std=gnu99
LDFLAGS ?=
PREFIX ?= /usr/local
DESTDIR ?=
CWD=$(shell pwd)

# Backends are selected at build time.  Set any of these to 0 to omit its
# emitter (and its embedded runtime) from the compiler and libaholyc.a.
AHOLYC_BACKEND_LLVM ?= 1
AHOLYC_BACKEND_C ?= 1
AHOLYC_BACKEND_JS ?= 1
CFLAGS += -DAHOLYC_BACKEND_LLVM=$(AHOLYC_BACKEND_LLVM) \
	-DAHOLYC_BACKEND_C=$(AHOLYC_BACKEND_C) \
	-DAHOLYC_BACKEND_JS=$(AHOLYC_BACKEND_JS)

LIBSRC = src/aholyc.c src/getopt.c src/lex.c src/parse.c src/effects.c src/util.c src/sb.c src/exe.c src/fmt.c
ifeq ($(AHOLYC_BACKEND_LLVM),1)
LIBSRC += src/back_ll.c
endif
ifeq ($(AHOLYC_BACKEND_C),1)
LIBSRC += src/back_c.c
endif
ifeq ($(AHOLYC_BACKEND_JS),1)
LIBSRC += src/back_js.c
endif
LIBOBJ = $(LIBSRC:.c=.o) src/embed.o
OBJ = src/main.o $(LIBOBJ)

all: aholyc

aholyc: src/main.o libaholyc.a
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ src/main.o libaholyc.a -ldl

libaholyc.a: $(LIBOBJ)
	$(AR) rcs $@ $(LIBOBJ)

$(OBJ): src/aholyc.h src/config.h
src/main.o src/getopt.o: src/getopt.h

src/config.h: FORCE
	@tmp=$@.tmp; \
	printf '%s\n' '/* Generated by Makefile; do not edit. */' \
		'#define AHOLYC_BACKEND_LLVM $(AHOLYC_BACKEND_LLVM)' \
		'#define AHOLYC_BACKEND_C $(AHOLYC_BACKEND_C)' \
		'#define AHOLYC_BACKEND_JS $(AHOLYC_BACKEND_JS)' > $$tmp; \
	if test -r $@ && cmp -s $$tmp $@; then rm -f $$tmp; else mv $$tmp $@; fi

# embedded runtime + prelude sources
src/embed.c: tools/file2c runtime/rt.c runtime/rt.js runtime/prelude.hc runtime/exe.hc FORCE
	@tmp=$@.tmp; { \
		if [ "$(AHOLYC_BACKEND_LLVM)" = 1 ] || [ "$(AHOLYC_BACKEND_C)" = 1 ]; then ./tools/file2c aholyc_i_rt_c_src runtime/rt.c; fi; \
		if [ "$(AHOLYC_BACKEND_JS)" = 1 ]; then ./tools/file2c aholyc_i_rt_js_src runtime/rt.js; fi; \
		./tools/file2c aholyc_i_prelude_hc runtime/prelude.hc; \
		if [ "$(AHOLYC_BACKEND_C)" = 1 ]; then ./tools/file2c aholyc_i_exe_hc runtime/exe.hc; fi; \
	} > $$tmp; \
	if test -r $@ && cmp -s $$tmp $@; then rm -f $$tmp; else mv $$tmp $@; fi

tools/file2c: tools/file2c.c
	$(CC) -O2 -o $@ tools/file2c.c

tests/lib_instances: tests/lib_instances.c libaholyc.a include/aholyc.h
	$(CC) $(CFLAGS) -Iinclude -o $@ tests/lib_instances.c libaholyc.a -ldl -pthread

test: aholyc tests/lib_instances
	sh tests/run.sh
	./tests/lib_instances

# normalize all HolyC sources in the repo (doc/format.md)
fmt: aholyc
	./aholyc fmt -w examples/*.HC tests/*.HC runtime/*.hc

clean:
	rm -f aholyc libaholyc.a tests/lib_instances $(OBJ) src/embed.c src/config.h tools/file2c
	rm -rf tests/out

install: aholyc libaholyc.a
	mkdir -p $(DESTDIR)$(PREFIX)/bin $(DESTDIR)$(PREFIX)/include $(DESTDIR)$(PREFIX)/lib
	cp aholyc $(DESTDIR)$(PREFIX)/bin/aholyc
	cp include/aholyc.h $(DESTDIR)$(PREFIX)/include/aholyc.h
	cp libaholyc.a $(DESTDIR)$(PREFIX)/lib/libaholyc.a

symstall: aholyc
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	rm -f $(DESTDIR)$(PREFIX)/bin/aholyc
	ln -fs $(CWD)/aholyc $(DESTDIR)$(PREFIX)/bin/aholyc

uninstall:
	rm -f $(DESTDIR)$(PREFIX)/bin/aholyc $(DESTDIR)$(PREFIX)/include/aholyc.h \
		$(DESTDIR)$(PREFIX)/lib/libaholyc.a

FORCE:

.PHONY: all test clean install uninstall FORCE
