all:
	mkdir -p ~/.vim/syntax
	mkdir -p ~/.vim/ftdetect
	cp syntax.vim ~/.vim/syntax/holyc.vim
	cp filetype.vim ~/.vim/ftdetect/holyc.vim
	rm -f ~/.vim/ftplugin/holyc.vim

uninstall:
	rm -f ~/.vim/syntax/holyc.vim
	rm -f ~/.vim/ftdetect/holyc.vim
	rm -f ~/.vim/ftplugin/holyc.vim
