name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test CC=clang

  mac-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: make test CC=clang
